name: aesth
description: A new Flutter package project.
version: 0.0.1
author: LIN Chen <entronad@gmail.com>
homepage: https://github.com/entronad/aesth

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  logging: ^0.11.3+2
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
